services:
  resourcespace:
    build: .
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - ./data/resourcespace/include:/var/www/html/include
      - ./data/resourcespace/filestore:/var/www/html/filestore
      - ./data/resourcespace/testdir:/srv/storage/testdir
    networks:
      - frontend
      - backend
    ports:
      - "80:80"

  mariadb:
    image: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - backend

  ai-faces:
    build: ./InsightFace
    depends_on:
      - mariadb
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./data/ai-faces:/root/.insightface/models
    command:
      [
        "python3",
        "/app/faces_service.py",
        "--db-host=mariadb",
        "--db-user=${MYSQL_USER}",
        "--db-pass=${MYSQL_PASSWORD}",
      ]

networks:
  frontend:
  backend:
