name: Publish Docker container

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Get tag name
      id: get_tag
      run: |
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/resourcespace:latest
          ghcr.io/${{ github.repository_owner }}/resourcespace:${{ steps.get_tag.outputs.tag }}